# ==================== UNIFIED CONFIG (MUJOCO & REAL) ====================
# Paths
policy_path: "{LEGGED_GYM_ROOT_DIR}/deploy/networks/go2/mk14/finetune_200.pt"
xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/go2/mujoco/scene_stairs_015.xml" # (SIM ONLY)

# Action & Observations
num_actions: 12
num_proprio: 53
enable_history: True
buffer_length: 9

# Protocols
msg_type: "go" # "hg" or "go" # (REAL ONLY)
lowcmd_topic: "rt/lowcmd"     # (REAL ONLY)
lowstate_topic: "rt/lowstate" # (REAL ONLY)


# Timing
simulation_duration: 200.0    # (MJ ONLY)
run_forever: True             # (MJ ONLY) 
simulation_dt: 0.005  
control_decimation: 4   # Controller update freq (simulation_dt * control_decimation=0.02; 50Hz)



# (REAL ONLY)
                    # hip, thigh, calf
leg_joint2motor_idx: [3, 4, 5,      # FL
                      0, 1, 2,      # FR
                      9, 10, 11,    # BL
                      6, 7, 8]      # BR
# fixes the order of the motors in the observation
# (e.g: Isaac and Mujoco are L-R-L-R, but Unitree Go2's joint order is R-L-R-L)

    # hip, thigh, calf
kps: [40.0, 40.0, 40.0,
      40.0, 40.0, 40.0,
      40.0, 40.0, 40.0,
      40.0, 40.0, 40.0]

    # hip, thigh, calf
kds: [1.0, 1.0, 1.0,
      1.0, 1.0, 1.0,
      1.0, 1.0, 1.0,
      1.0, 1.0, 1.0]

               # hip, thigh, calf
default_angles: [0.1, 0.8, -1.5,    # FL
                -0.1, 0.8, -1.5,    # FR
                 0.1, 1.0, -1.5,    # RL
                -0.1, 1.0, -1.5]    # RR

# Scales
ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]

# Clip values
clip_observations: 100.
clip_actions: 3.14   # Trained on 3.14

# Phase Features
period: 0.66         # [sec]
fr_offset: 0.0       # [%]
bl_offset: 0.0       # [%]
fl_offset: 0.5       # [%]
br_offset: 0.5       # [%]

# Remote controller scale
rc_scale: [0.8, 1.0, 1.57]