# ==================== UNIFIED CONFIG (MUJOCO & REAL) ====================

# Model (folder) name
model_name: &model "cheetah_estimator"

# Paths
policy_path: "{LEGGED_GYM_ROOT_DIR}/deploy/networks/go2/*model/policy.pt"
encoder_path: "{LEGGED_GYM_ROOT_DIR}/deploy/networks/go2/*model/encoder.pt"
estimator_path: "{LEGGED_GYM_ROOT_DIR}/deploy/networks/go2/*model/estimator.pt"

xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/go2/mujoco/scene_stairs_015.xml" 

# Action & Observations
num_actions: 12
num_proprio: 53
buffer_length: 10

# ===========================================================================================
# TODO: Make stumble penalization not just on foot, but also on calf too (DONE)

# TODO: Make period based on linear velocity

# TODO: Fix conflict between resampling commands and terrain level promotion/demotion logic.
#       i.e if the robot samples a fwd cmd and then a backward cmd, it can be wrongly demoted
#       to a lower level. SOLUTION: integrate the abs. vel./commanded vel. every env step

# TODO: Implement MIT rl_locomotion curriculum, if you have time. If not, extreme parkour.
# ===========================================================================================

# Phase Features
period: 0.35
fr_offset: 0.0 
bl_offset: 0.5
fl_offset: 0.0
br_offset: 0.5

# Protocols
msg_type: "go" # "hg" or "go" # (REAL ONLY)
lowcmd_topic: "rt/lowcmd"     # (REAL ONLY)
lowstate_topic: "rt/lowstate" # (REAL ONLY)


# Timing
simulation_dt: 0.005  
control_decimation: 4   # Controller update freq (simulation_dt * control_decimation=0.02; 50Hz)


# leg_joint2motor_idx: fixes the order of the motors in the observation
# (e.g: Isaac and Mujoco are L-R-L-R, but Unitree Go2's joint order is R-L-R-L)

                    # hip, thigh, calf
leg_joint2motor_idx: [3, 4, 5,    # FL
                      0, 1, 2,    # FR
                      9, 10, 11,  # BL
                      6, 7, 8]    # BR

    # hip, thigh, calf
kps: [40.0, 40.0, 40.0,
      40.0, 40.0, 40.0,
      40.0, 40.0, 40.0,
      40.0, 40.0, 40.0]

    # hip, thigh, calf
kds: [1.0, 1.0, 1.0,
      1.0, 1.0, 1.0,
      1.0, 1.0, 1.0,
      1.0, 1.0, 1.0]

                # hip, thigh, calf
default_angles: [0.1, 0.8, -1.5,    # Front left
                -0.1, 0.8, -1.5,    # Front right
                 0.1, 1.0, -1.5,    # Rear left
                -0.1, 1.0, -1.5]    # Rear right

# Empirically-tested joint ranges
# Hips (all):   [ -0.75,  0.75 ]
# Front thighs: [ -1.50,  1.75 ]
# Rear thighs:  [  0.00,  2.75 ]
# Calves (all): [ -2.75, -0.75 ]

# Scales
lin_vel_scale: 2.0 
ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25

# Clip values
clip_observations: 100.0
clip_actions: 3.8

# Remote controller scale
rc_scale: [2.0, 0.0, 1.5]