# ==================== UNIFIED CONFIG (MUJOCO & REAL) ====================
# Paths
policy_path: "{LEGGED_GYM_ROOT_DIR}/deploy/networks/go2/skipper_v6/3000.pt"
xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/go2/mujoco/scene_flat.xml" 

# Action & Observations
# enable_history: True
num_actions: 12
num_proprio: 53
buffer_length: 9

# Phase Features
period: 0.32                # TODO: Put Isaac period into config!!!!
fr_offset: 0.0 
bl_offset: 0.0
fl_offset: 0.25
br_offset: 0.25

# Protocols
msg_type: "go" # "hg" or "go" # (REAL ONLY)
lowcmd_topic: "rt/lowcmd"     # (REAL ONLY)
lowstate_topic: "rt/lowstate" # (REAL ONLY)


# Timing
simulation_dt: 0.005  
control_decimation: 4   # Controller update freq (simulation_dt * control_decimation=0.02; 50Hz)


# leg_joint2motor_idx: fixes the order of the motors in the observation
# (e.g: Isaac and Mujoco are L-R-L-R, but Unitree Go2's joint order is R-L-R-L)

                    # hip, thigh, calf
leg_joint2motor_idx: [3, 4, 5,      # FL
                      0, 1, 2,      # FR
                      9, 10, 11,    # BL
                      6, 7, 8]      # BR

    # hip, thigh, calf
kps: [40.0, 40.0, 40.0,
      40.0, 40.0, 40.0,
      40.0, 40.0, 40.0,
      40.0, 40.0, 40.0]

    # hip, thigh, calf
kds: [1.0, 1.0, 1.0,
      1.0, 1.0, 1.0,
      1.0, 1.0, 1.0,
      1.0, 1.0, 1.0]

               # hip, thigh, calf
default_angles: [0.1, 0.8, -1.5,    # FL
                -0.1, 0.8, -1.5,    # FR
                 0.1, 1.0, -1.5,    # RL
                -0.1, 1.0, -1.5]    # RR

# Scales
ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]

# Clip values
clip_observations: 100.0
clip_actions: 20.0          # NEW - Remember to match this!!!!

# Remote controller scale
rc_scale: [2.1, 0.5, 1.57]