
msg_type: "go"     # "hg" or "go"
imu_type: "pelvis"    # "torso" or "pelvis"

lowcmd_topic: "rt/lowcmd"
lowstate_topic: "rt/lowstate"

policy_path: "{LEGGED_GYM_ROOT_DIR}/deploy/networks/go2/rudolf_2_52k_cc.pt"
control_dt: 0.02  # control decimation * simulation_dt = 4 * 0.005 = 0.02 


# LEG 2 JOINT MOTOR INDEX: fixes the order of the motors in the observation
# Ex. Isaac and Mujoco are L R L R, but IRL the joint order is R L R L 

#                   hip, thigh, calf
leg_joint2motor_idx: [3, 4, 5,   # FL
                      0, 1, 2,   # FR
                      9, 10, 11, # BL
                      6, 7, 8]   # BR

#     hip, thigh, calf
kps: [40.0, 40.0, 40.0,
      40.0, 40.0, 40.0,
      40.0, 40.0, 40.0,
      40.0, 40.0, 40.0]

#     hip, thigh, calf
kds: [1.0, 1.0, 1.0,
      1.0, 1.0, 1.0,
      1.0, 1.0, 1.0,
      1.0, 1.0, 1.0]

default_angles: [
      0.1, 0.8, -1.5,   # FL
      -0.1, 0.8, -1.5,  # FR
      0.1, 1.0, -1.5,   # RL
      -0.1, 1.0, -1.5]  # RR

# Scales: match normalization class in Isaac cfg
ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]

# Match with network
num_actions: 12
num_obs: 53

# Phase gait stuff
period: 0.66
fr_offset: 0.0
bl_offset: 0.0
fl_offset: 0.5
br_offset: 0.5

# Cmd format: [forward, lateral, yaw]
max_cmd: [0.8, 0.5, 1.57]
