# Default config
policy_path: "{LEGGED_GYM_ROOT_DIR}/deploy/networks/go2/flat.pt" # PyTorch jit name/path
xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/go2/mujoco/scene.xml"

# Total simulation time
simulation_duration: 60.0
# Simulation time step
simulation_dt: 0.005
# Controller update frequency (meets the requirement of simulation_dt * control_decimation=0.02; 50Hz)
control_decimation: 4

# # GO2.XML JOINT ORDER (CHATGPT):
# FR_hip_joint = -0.1
# FR_thigh_joint = 0.8
# FR_calf_joint = -1.5
# FL_hip_joint = 0.1
# FL_thigh_joint = 0.8
# FL_calf_joint = -1.5
# RR_hip_joint = -0.1
# RR_thigh_joint = 1.0
# RR_calf_joint = -1.5
# RL_hip_joint = 0.1
# RL_thigh_joint = 1.0
# RL_calf_joint = -1.5


# PD gains matching Isaac Gym's stiffness=20, damping=0.5
kps: [20, 20, 20,
      20, 20, 20,
      20, 20, 20,
      20, 20, 20]
kds: [0.5, 0.5, 0.5,
      0.5, 0.5, 0.5,
      0.5, 0.5, 0.5,
      0.5, 0.5, 0.5]

default_angles: [-0.1, 0.8, -1.5,
                 0.1, 0.8, -1.5,
                 -0.1, 1.0, -1.5,
                 0.1, 1.0, -1.5]


# From normalization class in Isaac cfg
ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.5    # From control class in Isaac cfg
cmd_scale: [2.0, 2.0, 0.25]

num_actions: 12    # must match your policy output
num_obs: 48        # must match your policy input - 48 when mesh_type = 'plane', 235 otherwise...

# Example initial command if your policy uses (forward, lateral, yaw)
cmd_init: [0.5, 0.0, 0.0]