# Default config
policy_path: "{LEGGED_GYM_ROOT_DIR}/deploy/networks/go2/bambi12.pt" # PyTorch jit name/path
xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/go2/mujoco/scene.xml"

# Total simulation time
simulation_duration: 60.0
# Simulation time step
simulation_dt: 0.005
# Controller update frequency (meets the requirement of simulation_dt * control_decimation=0.02; 50Hz)
control_decimation: 4

# PD gains matching Isaac Gym's stiffness=20, damping=0.5
kps: [20, 20, 20,
      20, 20, 20,
      20, 20, 20,
      20, 20, 20]
kds: [0.5, 0.5, 0.5,
      0.5, 0.5, 0.5,
      0.5, 0.5, 0.5,
      0.5, 0.5, 0.5]

# default_angles: [-0.1, 0.8, -1.5,
#                  0.1, 0.8, -1.5,
#                  -0.1, 1.0, -1.5,
#                  0.1, 1.0, -1.5]
# default_angles: [
#       0, 0.8, -1.5, 
#       0, 0.8, -1.5,
#       0, 0.8, -1.5, 
#       0, 0.8, -1.5, 
#       ]
default_angles: [
      0, 0.9, -1.8,
      0, 0.9, -1.8,
      0, 0.9, -1.8, 
      0, 0.9, -1.8,
      ]

# From normalization class in Isaac cfg
lin_vel_scale: 2.0
ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25    # from Isaac Gym
cmd_scale: [2.0, 2.0, 0.25]

num_actions: 12    # must match your policy output
num_obs: 48        # must match your policy input - 48 when mesh_type = 'plane', 235 otherwise...

# Example initial command if your policy uses (forward, lateral, yaw)
cmd_init: [0.1, 0.0, 0.0]