# Default config
policy_path: "{LEGGED_GYM_ROOT_DIR}/deploy/networks/go2/rudolf_2_command_curriculum.pt"
xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/go2/mujoco/scene_mountain.xml"

# Total simulation time (seconds)
simulation_duration: 200.0
run_forever: True

# Simulation time step
simulation_dt: 0.005

# Controller update frequency (meets the requirement of simulation_dt * control_decimation=0.02; 50Hz)
control_decimation: 4

# Match PD gains in Isaac Gym cfg
kp_gains: [20, 20, 20,
      20, 20, 20,
      20, 20, 20,
      20, 20, 20]

# # ======= ORIGINAL DAMPING =======
# kd_gains: [0.5, 0.5, 0.5,
#       0.5, 0.5, 0.5,
#       0.5, 0.5, 0.5,
#       0.5, 0.5, 0.5]
# # ================================


# ======= 2X DAMPING TEST! =======
kd_gains: [1.0, 1.0, 1.0,
      1.0, 1.0, 1.0,
      1.0, 1.0, 1.0,
      1.0, 1.0, 1.0]
# ================================

default_angles: [
      0.1, 0.8, -1.5,   # FL
      -0.1, 0.8, -1.5,  # FR
      0.1, 1.0, -1.5,   # RL
      -0.1, 1.0, -1.5]  # RR



# Match normalization class in Isaac Gym cfg
lin_accel_scale: 1.0    # NEW
lin_vel_scale: 2.0
ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]

# Match with network
num_actions: 12         # 12 for go2
num_obs: 53        


# Cmd: ([forward, lateral, yaw])
command: [3., .0, .0]